import Foundation

/// A single sidebar conversation entry.
///
/// This is a plain, `Sendable` value type — the persistence-layer
/// SwiftData model lives in `Persistence/ChatterBatSchemaV1.swift` and is
/// never exposed outside `ConversationRepository`, per the brief's rule
/// against passing SwiftData model instances between actors. As of
/// Stage 4, `ConversationRepository` is the source of truth for this
/// type in the running app; `AppViewModel`'s demo-data initializer is
/// retained only for previews/tests that don't need real persistence.
struct Conversation: Identifiable, Hashable, Sendable {
    let id: UUID
    var title: String
    /// A short, locally-derived preview of the conversation's most
    /// recent message content — never generated by a model call, per
    /// the brief.
    var lastMessagePreview: String
    var updatedAt: Date

    init(
        id: UUID = UUID(),
        title: String,
        lastMessagePreview: String = "",
        updatedAt: Date = .now
    ) {
        self.id = id
        self.title = title
        self.lastMessagePreview = lastMessagePreview
        self.updatedAt = updatedAt
    }
}
